# Generated by Django 4.2.1 on 2023-09-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('user_email', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('user_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('for_post', models.CharField(blank=True, choices=[('Moderator', 'Moderator'), ('Railway Admin', 'Railway Admin'), ('Normal User', 'Normal User'), ('Superuser', 'Superuser')], default=None, max_length=100, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('seen', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=12, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user_onboarding.request_user')),
            ],
        ),
    ]
