# Generated by Django 4.2.1 on 2023-09-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Request_User',
        ),
    ]
